android-sdk:
  image: tibo43/android-sdk:latest
  volumes:
    - .:/root/project
    - /var/lib/jenkins/android.keystore:/root/android.keystore
  working_dir: /root/project
  environment:
    - HOST_UID=${HOST_UID}
    - HOST_GID=${HOST_GID}
    - JAVA_OPTS="-Xmx1536M"
    - PATH=/root/android-sdk-linux/tools:/root/android-sdk-linux/platform-tools:/root/android-sdk-linux/build-tools/28.0.3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  command: >
    bash -c "npm install &&
             rm -f node_modules/react-native/local-cli/core/__fixtures__/files/package.json ;
             rm -rf build && npm run tsc:build &&
             cd android &&
             rm -rf ./app/build &&
             ./gradlew clean &&
             cd .. &&
             react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/generated/res/react/release &&
             cd android &&
             ./gradlew assembleRelease &&
             zipalign 4 android/app/build/outputs/apk/release/app-release-unsigned.apk android/app/build/outputs/apk/release/app-release-signed.apk &&
             echo android | apksigner sign --ks /root/android.keystore --ks-key-alias android android/app/build/outputs/apk/release/app-release-signed.apk &&
             chown -R $HOST_UID:$HOST_GID -R ."
